#!/usr/bin/env python3
"""Build the generated-asset manifest for Blender Asset Forge outputs."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = ROOT / "assets/Source/Blender"
PROD_ROOT = ROOT / "assets/Production/Generated"
REVIEW_ROOT = ROOT / "artifacts/asset-review"
MANIFEST = PROD_ROOT / "asset_manifest.json"
INSPECT = r'''
import json, sys, bpy
path = sys.argv[sys.argv.index('--') + 1]
bpy.ops.wm.open_mainfile(filepath=path)
meshes = [o for o in bpy.context.scene.objects if o.type == 'MESH']
materials = sorted({slot.material.name for o in meshes for slot in o.material_slots if slot.material})
triangles = 0
issues = []
for obj in meshes:
    if not obj.name: issues.append('empty object name')
    if not obj.material_slots: issues.append(f'missing material slot: {obj.name}')
    if obj.get('titancraft_collision', 'none') != 'none': issues.append(f'collision metadata is not none: {obj.name}')
    depsgraph = bpy.context.evaluated_depsgraph_get()
    mesh = obj.evaluated_get(depsgraph).to_mesh()
    for poly in mesh.polygons: triangles += max(1, len(poly.vertices) - 2)
    obj.evaluated_get(depsgraph).to_mesh_clear()
print(json.dumps({'material_slots': materials, 'triangle_count': triangles, 'validation_status': 'PASS' if meshes and not issues else 'FAIL', 'issues': issues}, sort_keys=True))
if issues or not meshes: raise SystemExit(2)
'''


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def inspect_blend(path: Path) -> dict[str, object]:
    result = subprocess.run(["blender", "--background", "--python-expr", INSPECT, "--", str(path)], text=True, capture_output=True)
    if result.returncode != 0:
        return {"material_slots": [], "triangle_count": None, "validation_status": "FAIL", "issues": [result.stderr.strip() or result.stdout.strip()]}
    lines = [line for line in result.stdout.splitlines() if line.startswith("{")]
    return json.loads(lines[-1]) if lines else {"material_slots": [], "triangle_count": None, "validation_status": "FAIL", "issues": ["missing inspect json"]}


def review_paths(asset_name: str) -> list[str]:
    explicit = REVIEW_ROOT / asset_name
    if explicit.exists():
        return [str(path.relative_to(ROOT)) for path in sorted(explicit.glob("*.png"))]
    slug = asset_name.removeprefix("TC_").replace("_", "-").lower()
    folder = REVIEW_ROOT / slug
    return [str(path.relative_to(ROOT)) for path in sorted(folder.glob("*.png"))]


MVP_PACK_V1_ASSETS = {
    "TC_PROP_Workbench_V1",
    "TC_PROP_Beacon_Dormant_V1",
    "TC_PROP_Beacon_Active_V1",
    "TC_PICKUP_Metal_V1",
    "TC_PICKUP_Biomass_V1",
    "TC_PICKUP_Electronics_V1",
    "TC_PICKUP_Component_V1",
    "TC_CHAR_GalaxabrainScout_V1",
    "TC_PLAYER_MechanicalArm_V1",
    "TC_PROP_SavePoint_V1",
    "TC_ENV_CrashDebris_A_V1",
}


def asset_overrides(name: str) -> dict[str, object]:
    if name in MVP_PACK_V1_ASSETS:
        return {
            "classification": "production-candidate",
            "source_recipe": "tools/blender/create_mvp_asset_pack_v1.py",
            "created_by_tool": "tools/blender/create_mvp_asset_pack_v1.py + tools/blender/export_asset.py",
            "binary_delivery": "generated by Blender Asset Forge / GitHub Actions; .blend, .glb, and review PNGs are committed back to the branch by .github/workflows/blender-asset-forge.yml (see studio/decisions/commit-generated-blender-binaries.md)",
            "notes": "MVP Asset Pack V1 concept-sheet candidate (docs/art/briefs/mvp-asset-pack-v1.md); visual-only, collisionless, not integrated into production scenes.",
            "verdict": "TC_MVP_ASSET_PACK_V1_REVIEW_ARTIFACTS_READY",
        }
    if name == "TC_HeavyCrashHull_V1":
        return {
            "classification": "production-candidate",
            "source_recipe": "tools/blender/create_heavy_crash_hull_v1.py",
            "created_by_tool": "tools/blender/create_heavy_crash_hull_v1.py + tools/blender/export_asset.py",
            "binary_delivery": "generated by Blender Asset Forge / GitHub Actions; .blend, .glb, and review PNGs are committed back to the branch by .github/workflows/blender-asset-forge.yml (see studio/decisions/commit-generated-blender-binaries.md)",
            "notes": "Project-authored standalone heavy crashed hull module candidate; visual-only, collisionless, not Stage A scene art, not integrated into Main.tscn. Binary .blend/.glb are generated artifacts, not source-controlled binaries.",
            "verdict": "TC_HEAVY_CRASH_HULL_V1_REVIEW_ARTIFACTS_READY",
        }
    if name == "TC_LightingReference_V1":
        return {
            "classification": "production-candidate",
            "source_recipe": "tools/blender/create_lighting_reference_kit_v1.py",
            "created_by_tool": "tools/blender/create_lighting_reference_kit_v1.py + tools/blender/export_asset.py",
            "binary_delivery": "generated by Blender Asset Forge / GitHub Actions; .blend, .glb, and review PNGs are committed back to the branch by .github/workflows/blender-asset-forge.yml (see studio/decisions/commit-generated-blender-binaries.md)",
            "notes": "Stage B candidate #9 (docs/art/STAGE_B_ORCHESTRATION_BRIEF.md); functional glow-color/intensity reference reusing the exact emissive values from tools/blender/create_mvp_asset_pack_v1.py. Visual-only, collisionless, not integrated into any production scene.",
            "verdict": "TC_LIGHTING_REFERENCE_V1_REVIEW_ARTIFACTS_READY",
        }
    return {}


def build_manifest() -> dict[str, object]:
    entries = []

    # Load existing manifest to preserve procedurally generated asset metadata
    existing_entries = {}
    if MANIFEST.exists():
        try:
            with open(MANIFEST) as f:
                existing = json.load(f)
                existing_entries = {e["asset_name"]: e for e in existing.get("entries", [])}
        except Exception:
            pass

    for glb in sorted(PROD_ROOT.glob("**/*.glb")):
        name = glb.stem

        # Check if this is a procedurally generated asset with existing valid metadata
        if name in existing_entries:
            existing = existing_entries[name]
            # Preserve procedurally generated assets (those with created_by_tool like create_terrain_*)
            if (existing.get("source_blend") is None and
                existing.get("created_by_tool") and
                "create_" in existing.get("created_by_tool", "") and
                existing.get("validation_status") != "FAIL"):
                # Update only the GLB hash and review artifacts, preserve other metadata
                existing["production_sha256"] = sha256(glb)
                existing["production_export"] = str(glb.relative_to(ROOT))
                existing["review_artifacts"] = review_paths(name)
                entries.append(existing)
                continue

        # For non-procedural assets, discover source .blend and rebuild entry
        candidates = sorted(SOURCE_ROOT.glob(f"**/{name}.blend"))
        source = candidates[0] if candidates else None
        inspection = inspect_blend(source) if source else {"material_slots": [], "triangle_count": None, "validation_status": "FAIL", "issues": ["missing source blend"]}
        entry = {
            "asset_name": name,
            "classification": "pipeline-test" if name == "TC_TestCrate" else "generated",
            "source_blend": str(source.relative_to(ROOT)) if source else None,
            "source_sha256": sha256(source) if source else None,
            "production_export": str(glb.relative_to(ROOT)),
            "production_sha256": sha256(glb),
            "export_format": "GLB",
            "created_by_tool": "tools/blender/create_test_crate.py" if name == "TC_TestCrate" else "tools/blender/export_asset.py",
            "material_slots": inspection["material_slots"],
            "validation_status": inspection["validation_status"],
            "triangle_count": inspection["triangle_count"],
            "review_artifacts": review_paths(name),
            "collision_policy": "none",
            "runtime_mesh_generation": False,
            "license": "project-authored",
            "notes": "Non-production Blender Asset Forge test crate; do not use as final TitanCraft art." if name == "TC_TestCrate" else "Generated asset entry.",
        }
        entry.update(asset_overrides(name))
        entries.append(entry)
    return {
        "schema": "titancraft.blender_asset_forge.manifest.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "entries": entries,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="discover generated asset entries and report status without writing asset_manifest.json",
    )
    parser.add_argument(
        "--allow-empty",
        action="store_true",
        help="allow overwriting an existing manifest with zero discovered generated assets",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = build_manifest()
    entries = manifest["entries"]

    if args.check:
        print(f"ASSET_MANIFEST_CHECK {MANIFEST} entries={len(entries)} write=skipped")
        if not entries:
            print("ASSET_MANIFEST_CHECK_WARNING no generated .glb artifacts discovered; existing manifest was not modified")
        return

    if not entries and MANIFEST.exists() and not args.allow_empty:
        print(
            f"ASSET_MANIFEST_PRESERVED {MANIFEST} entries=0 "
            "reason=no_generated_artifacts use --allow-empty to overwrite"
        )
        return

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"ASSET_MANIFEST_WRITTEN {MANIFEST} entries={len(entries)}")


if __name__ == "__main__":
    main()
