#!/usr/bin/env python3
"""Build a Windows playtest journey verdict draft from generated CI evidence.

Reads the smoke report JSON produced by the windows-playtest-journey workflow
plus the capture directory listing, and emits a verdict draft that already
carries every machine-verifiable field. The Visual Reviewer agent (or a
human) then opens the capture PNGs, replaces the PENDING verdicts, and
commits the result to docs/production/playtests/.

Usage:
  python3 tools/build_playtest_verdict_draft.py smoke_report.json captures_dir out.md
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: build_playtest_verdict_draft.py smoke_report.json captures_dir out.md")
        return 2

    report_path, captures_dir, out_path = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    report = json.loads(report_path.read_text(encoding="utf-8"))
    pngs = sorted(str(p) for p in captures_dir.rglob("*.png")) if captures_dir.exists() else []

    png_lines = "\n".join(f"- `{p}`" for p in pngs) if pngs else "- (no captures found — capture job must be investigated before any PASS)"
    windows_capture = report.get("windows_capture_png") or "not captured (best-effort step did not produce a frame)"

    body = f"""# Windows Playtest Journey Verdict — {date.today().isoformat()}

Generated by `windows-playtest-journey` from machine evidence. Replace every
`PENDING` after opening the cited PNGs. Validation:
`python3 tools/validate_playtest_evidence.py` (committed) — subjective feel
adjectives require a dated `Human note (YYYY-MM-DD)` and will fail validation
otherwise.

## Build Provenance

- Executable: `{report.get("executable", "builds/Windows/TitanCraft.exe")}`
- SHA-256: `{report.get("sha256", "MISSING")}`
- Workflow run id: {report.get("run_id", "MISSING")} (workflow run `{report.get("workflow", "windows-playtest-journey")}`, runs/{report.get("run_id", "0")})
- Runner: {report.get("runner_os", "windows-latest")} {report.get("runner_os_version", "")}
- Commit: `{report.get("sha", "MISSING")}`

## Windows Smoke Evidence

- Artifact: `windows-playtest-bundle` (contains `smoke_report.json`, export log, exe hash)
- Headless smoke: exit_code {report.get("smoke_exit_code", "MISSING")} after {report.get("smoke_frames", "?")} frames in {report.get("smoke_wall_seconds", "?")} s wall time on the Windows runner
- Frame-pacing proxy (headless, not rendered performance): {report.get("frames_per_second_proxy", "?")} frames/s
- Windows on-screen capture (best effort): {windows_capture}

## Aesthetic Verdict

Reviewer: Visual Reviewer agent per `studio/decisions/quality_benchmark_v2_agent_gate_delegation.md`
(open every PNG below before judging; name focal point, route readability, silhouette, scale,
material coherence).

Opened captures:
{png_lines}

Diagnosis: PENDING

Verdict: PENDING

## Feel Evidence

No dated human note is present in this draft. Per the delegation ADR, feel is
reported through measured proxies only: smoke exit code, frame-pacing proxy
({report.get("frames_per_second_proxy", "?")} frames/s headless), and the integration-suite pass recorded in the
workflow logs. Subjective feel adjectives are forbidden in this document unless a
`Human note (YYYY-MM-DD)` paragraph is added.

## Final Verdict

Verdict: PENDING

Scope note: this document gates the Windows playtest journey only. It does not
approve Stage B, marketing claims, or scene integration of reviewed assets.
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body, encoding="utf-8")
    print(f"PLAYTEST_VERDICT_DRAFT_WRITTEN {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
